### ISSUE TITLE
Code has build errors with Java 17

### ISSUE THREAD

**Issue by ctrueden** [scijava/scijava#103]
```
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.205 s <<< FAILURE! - in org.scijava.persist.SerializationTests
[ERROR] testCircleObject  Time elapsed: 0.184 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make field int org.scijava.persist.Circle.radius accessible: module org.scijava.persist does not "opens org.scijava.persist" to module com.google.gson
	at org.scijava.persist@0-SNAPSHOT/org.scijava.persist.SerializationTests.testSerializationDeserialization(SerializationTests.java:76)
	at org.scijava.persist@0-SNAPSHOT/org.scijava.persist.SerializationTests.testCircleObject(SerializationTests.java:50)

[ERROR] testDrawingObject  Time elapsed: 0.01 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make field int org.scijava.persist.Circle.radius accessible: module org.scijava.persist does not "opens org.scijava.persist" to module com.google.gson
	at org.scijava.persist@0-SNAPSHOT/org.scijava.persist.SerializationTests.testSerializationDeserialization(SerializationTests.java:76)
	at org.scijava.persist@0-SNAPSHOT/org.scijava.persist.SerializationTests.testDrawingObject(SerializationTests.java:62)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   SerializationTests.testCircleObject:50->testSerializationDeserialization:76 » InaccessibleObject
[ERROR]   SerializationTests.testDrawingObject:62->testSerializationDeserialization:76 » InaccessibleObject
[INFO] 
```

**Comment by gselzer** [comment]
I fixed the failures on Java 17 with https://github.com/scijava/incubator/commit/25420aa353ad520f3c3ff81ea7251513c392b977.

With that in mind, when I added `<scijava.jvm.version>17</scijava.jvm.version>` to the base incubator POM, I got the following error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.3.0:enforce (enforce-rules) on project scijava-incubator: Execution enforce-rules of goal org.apache.maven.plugins:maven-enforcer-plugin:3.3.0:enforce failed: Unknown JDK version given. Should be something like "1.7", "8", "11", "12" -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

Can others reproduce, @hinerm   @ctrueden? I couldn't find anything online on fixing this...

**Comment by ctrueden** [comment]
@gselzer The problem is the extra-enforcer-rules version.
* https://github.com/mojohaus/extra-enforcer-rules/blob/d78f92f24cabef59866493817f138529266f98cc/src/main/java/org/codehaus/mojo/extraenforcer/dependencies/EnforceBytecodeVersion.java#L245-L251

Version 1.2 is too old:
* https://github.com/mojohaus/extra-enforcer-rules/blob/extra-enforcer-rules-1.2/src/main/java/org/apache/maven/plugins/enforcer/EnforceBytecodeVersion.java#L67-L98

Version 1.4 is new enough. Try building with `-Dextra-enforcer-rules.version=1.4` and see if that solves the problem. Ideally we'd be on the latest, which is 1.6.1, but maybe it broke something when I tried to upgrade past 1.2? I forget...

**Comment by gselzer** [comment]
> Version 1.4 is new enough. Try building with `-Dextra-enforcer-rules.version=1.4` and see if that solves the problem. Ideally we'd be on the latest, which is 1.6.1, but maybe it broke something when I tried to upgrade past 1.2? I forget...

Fortunately, that fixes the above error, but it presents a new error:
```
ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.1.0:enforce (enforce-rules) on project scijava-incubator: Execution enforce-rules of goal org.apache.maven.plugins:maven-enforcer-plugin:3.1.0:enforce failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-enforcer-plugin:3.1.0:enforce: java.lang.NoSuchMethodError: 'org.apache.maven.shared.dependency.graph.DependencyNode org.apache.maven.shared.dependency.graph.DependencyGraphBuilder.buildDependencyGraph(org.apache.maven.project.ProjectBuildingRequest, org.apache.maven.artifact.resolver.filter.ArtifactFilter)'
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.maven.plugins:maven-enforcer-plugin:3.1.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/gselzer/.m2/repository/org/apache/maven/plugins/maven-enforcer-plugin/3.1.0/maven-enforcer-plugin-3.1.0.jar
[ERROR] urls[1] = file:/home/gselzer/.m2/repository/org/scijava/scijava-maven-plugin/2.2.0/scijava-maven-plugin-2.2.0.jar
[ERROR] urls[2] = file:/home/gselzer/.m2/repository/guru/nidi/jdepend/2.9.5/jdepend-2.9.5.jar
[ERROR] urls[3] = file:/home/gselzer/.m2/repository/net/sf/jgrapht/jgrapht/0.8.3/jgrapht-0.8.3.jar
[ERROR] urls[4] = file:/home/gselzer/.m2/repository/javax/enterprise/cdi-api/1.2/cdi-api-1.2.jar
[ERROR] urls[5] = file:/home/gselzer/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.5/org.eclipse.sisu.inject-0.3.5.jar
[ERROR] urls[6] = file:/home/gselzer/.m2/repository/org/sonatype/sisu/sisu-guice/3.2.3/sisu-guice-3.2.3-no_aop.jar
[ERROR] urls[7] = file:/home/gselzer/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[8] = file:/home/gselzer/.m2/repository/com/google/guava/guava/16.0.1/guava-16.0.1.jar
[ERROR] urls[9] = file:/home/gselzer/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[10] = file:/home/gselzer/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[11] = file:/home/gselzer/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-annotations/3.6.4/maven-plugin-annotations-3.6.4.jar
[ERROR] urls[12] = file:/home/gselzer/.m2/repository/org/apache/maven/shared/maven-artifact-transfer/0.9.1/maven-artifact-transfer-0.9.1.jar
[ERROR] urls[13] = file:/home/gselzer/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/3.2.0/maven-common-artifact-filters-3.2.0.jar
[ERROR] urls[14] = file:/home/gselzer/.m2/repository/org/apache/xbean/xbean-reflect/3.7/xbean-reflect-3.7.jar
[ERROR] urls[15] = file:/home/gselzer/.m2/repository/com/google/collections/google-collections/1.0/google-collections-1.0.jar
[ERROR] urls[16] = file:/home/gselzer/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.24/plexus-interpolation-1.24.jar
[ERROR] urls[17] = file:/home/gselzer/.m2/repository/org/codehaus/plexus/plexus-utils/3.4.2/plexus-utils-3.4.2.jar
[ERROR] urls[18] = file:/home/gselzer/.m2/repository/org/scijava/scijava-common/2.87.0/scijava-common-2.87.0.jar
[ERROR] urls[19] = file:/home/gselzer/.m2/repository/org/scijava/parsington/2.0.0/parsington-2.0.0.jar
[ERROR] urls[20] = file:/home/gselzer/.m2/repository/org/bushe/eventbus/1.4/eventbus-1.4.jar
[ERROR] urls[21] = file:/home/gselzer/.m2/repository/org/apache/maven/shared/maven-dependency-tree/2.2/maven-dependency-tree-2.2.jar
[ERROR] urls[22] = file:/home/gselzer/.m2/repository/org/codehaus/plexus/plexus-component-annotations/2.1.1/plexus-component-annotations-2.1.1.jar
[ERROR] urls[23] = file:/home/gselzer/.m2/repository/org/codehaus/mojo/extra-enforcer-rules/1.4/extra-enforcer-rules-1.4.jar
[ERROR] urls[24] = file:/home/gselzer/.m2/repository/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
[ERROR] urls[25] = file:/home/gselzer/.m2/repository/org/apache/maven/enforcer/enforcer-api/3.1.0/enforcer-api-3.1.0.jar
[ERROR] urls[26] = file:/home/gselzer/.m2/repository/org/apache/maven/enforcer/enforcer-rules/3.1.0/enforcer-rules-3.1.0.jar
[ERROR] urls[27] = file:/home/gselzer/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.3.4/maven-shared-utils-3.3.4.jar
[ERROR] urls[28] = file:/home/gselzer/.m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
[ERROR] urls[29] = file:/home/gselzer/.m2/repository/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
[ERROR] urls[30] = file:/home/gselzer/.m2/repository/org/apache-extras/beanshell/bsh/2.0b6/bsh-2.0b6.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>org.scijava:scijava-incubator:0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] 

```

**Comment by ctrueden** [comment]
Yep. It's because the scijava-maven-plugin has its own custom enforcer rules, and depends on some pinned versions of core Maven/Plexus components. I have tried upgrading it to latest, but the Maven/Plexus component collection is/was a tangled mess, and I couldn't figure out how to do it. But it's been months/years since last time I tried, so maybe it's better now. The next step would be to upgrade https://github.com/scijava/scijava-maven-plugin to the latest pom-scijava, remove all dependency pins, and fix all API incompatibilities in the codebase, attempting to keep all tests working. Then we can release a new scijava-maven-plugin + pom-scijava-base + pom-scijava containing the update, which should allow us to update extra-enforcer-rules. We didn't do it before because we didn't need it (extra-enforcer-rules 1.2 was good enough), but if we want proper Java 17 support, we'll need to do it... or else drop the use of extra-enforcer-rules from our build system, which would be a shame.

**Comment by gselzer** [comment]
> The next step would be to upgrade https://github.com/scijava/scijava-maven-plugin to the latest pom-scijava, remove all dependency pins, and fix all API incompatibilities in the codebase, attempting to keep all tests working.

@ctrueden @hinerm I was able to update scijava-maven-plugin to pom-scijava 36 on [this branch](https://github.com/scijava/scijava-maven-plugin/tree/update-to-pom-scijava-36) with all tests passing. 

Not sure what you mean by "remove all dependency pins", if you mean [these](https://github.com/scijava/scijava-maven-plugin/blob/27ba363dfecb0682579c0818f832c19ea315ccef/pom.xml#L141-L155) then I was unable to take them out - I also deleted the version pins in the dependencies below, but maven complained - I thought the versions would just be taken from pom-scijava?
