### ISSUE TITLE
Optional parameters don't work outside of scijava-ops-engine

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#110]
Declaring parameters `@Optional` outside of the `scijava-ops-engine` component leads to `IllegalAccessError`.

For example, `DefaultMeanFilter` should have an optional `OutOfBoundsFactory` parameter:
```java
public void compute(final RandomAccessibleInterval<T> input, final Shape inputNeighborhoodShape,
		@Optional OutOfBoundsFactory<T, RandomAccessibleInterval<T>> outOfBoundsFactory,
		final RandomAccessibleInterval<V> output) {
	if (outOfBoundsFactory == null)
		outOfBoundsFactory = new OutOfBoundsBorderFactory<>();
	RandomAccessibleInterval<T> extended = Views.interval((Views.extend(input, outOfBoundsFactory)), input);
	mapper.compute(extended, inputNeighborhoodShape, statsOp, output);
}
```

But attempting to match this with:
```java
ops.op("filter.mean").input(img, shape).output(output).compute();
```
produces the following exception:
```
java.lang.IllegalAccessError: class org.scijava.ops.engine.reduce.DefaultMeanFilterReduction1RandomAccessibleInterval_Shape_RandomAccessibleInterval_RandomAccessibleInterval (in module org.scijava.ops.engine) cannot access class net.imagej.ops2.filter.mean.DefaultMeanFilter (in module net.imagej.ops2) because module org.scijava.ops.engine does not read module net.imagej.ops2

	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.reduce.DefaultMeanFilterReduction1RandomAccessibleInterval_Shape_RandomAccessibleInterval_RandomAccessibleInterval.compute(DefaultMeanFilterReduction1RandomAccessibleInterval_Shape_RandomAccessibleInterval_RandomAccessibleInterval.java)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.matcher.impl.OpWrappers$Computer2OpWrapper$1GenericTypedComputer2.compute(OpWrappers.java:844)
	at org.scijava.ops.api@0-SNAPSHOT/org.scijava.ops.api.OpBuilder$Arity2_IV_OV.compute(OpBuilder.java:1020)
```

This means that `scijava.ops.engine` would need a `requires xxxx` on any package using `@Optional` in *its own `module-info.java`, which of course would be cyclic and also non-extensible.

**Comment by hinerm** [comment]
Branch started: https://github.com/scijava/incubator/tree/imagej/imagej-ops2/optional-params

**Comment by gselzer** [comment]
Okay, so I have things working on that branch, but I still don't understand why we cannot directly call the functional method of the functional interface. I can do crazy things inside of the javassist reduced Op, like making a new instance of the Op class!

I think we should do more investigation, but I think I've run out of time today to try...

**Comment by hinerm** [comment]
> I think we should do more investigation, but I think I've run out of time today to try...

So, ultimately, without this change, the `compute` method is being called in the javassist-created class:
```
org.scijava.ops.engine.reduce.DefaultMeanFilterReduction1RandomAccessibleInterval_Shape_RandomAccessibleInterval_RandomAccessibleInterval
```

Following JPMS rules of callability I would not expect this class to have access to the underlying op's `compute`, since it's not in the same package as the original op (`net.imagej.ops2.filter.mean`) and, as the error message indicates, the module it *is* in doesn't have read access to `ops2.filter.mean`.

But, because `compute` is a method of an interface that *is* read by the javassist class's module, I don't understand why it doesn't work.

> I can do crazy things inside of the javassist reduced Op, like making a new instance of the Op class!

Do you mean via reflection, e.g. `Class.newInstance()`? Or actually calling `new ClassName()`? If it's via reflection, that seems to be working as expected since `opens..to..` gives reflection access (and thus the solution to use reflection seems reasonable).

things I tried:
* `exports..to..` doesn't work since it isn't this mysterious "read" access that is only granted by `requires`
* Parameterizing the op with core module classes (FAILED)
* Running in python without JPMS (passed!)
* Casting the Op to the functional interface that we have access to (FAILED)
* Trying to learn more about Javassist and JPMS interactions (Couldn't find anything)
* Forcing the Javassist Op to be in the same `net.imagej...` package as the original op (FAILED)

Some thoughts:
* It feels weird to me that our javassist-created Op is a class in an `org.scijava` package regardless of where it came from...
* Is there a way to call the original Op's method without a reference to its class? Can we create a copy of that method inside our new Javassist op itself? and just delegate to ourselves?
* The Javassist Op doesn't know any of the generic types of the interface it's implementing, right? Does that affect type safety guarantees of future matches in a given session?
