### ISSUE TITLE
`ops.op("math.subtract")` does not work

### ISSUE THREAD

**Issue by elevans** [scijava/scijava#134]
While testing SciJavaOps in the Fiji script editor (using Jython) I discovered that I was unable to use the `"math.subtract"` op to subtract two images from each other.

Here is a minimal example you can run with an open 2D image in Fiji:

```python
#@ Img img_in

# get op environoment
from org.scijava.ops.api import OpEnvironment
ops = OpEnvironment.getEnvironment()

# create gauss blur of image
gauss = ops.op("filter.gauss").arity2().input(img_in, 3.0).apply()

# subtract gauss blur from input image
res = ops.op("math.subtract").arity2().input(img_in, gauss).apply()
```

This produces the following output:

```python
...
... 24 more
	Suppressed: org.scijava.ops.api.features.OpMatchingException: No matching 'math.subtract/java.util.function.BiFunction<net.imagej.ImgPlus<net.imglib2.type.numeric.integer.UnsignedShortType>, net.imagej.ImgPlus<net.imglib2.type.numeric.integer.UnsignedShortType>, java.lang.Object>' op

Request:
-	Name: "math.subtract", Types: java.util.function.BiFunction<net.imagej.ImgPlus<net.imglib2.type.numeric.integer.UnsignedShortType>, net.imagej.ImgPlus<net.imglib2.type.numeric.integer.UnsignedShortType>, java.lang.Object>
Input Types: 
		* net.imagej.ImgPlus<net.imglib2.type.numeric.integer.UnsignedShortType>
		* net.imagej.ImgPlus<net.imglib2.type.numeric.integer.UnsignedShortType>
Output Type: 
		* java.lang.Object

Candidates:
-	 No candidates found!
		at org.scijava.ops.api.features.MatchingResult.singleMatch(MatchingResult.java:67)
		at org.scijava.ops.engine.matcher.impl.RuntimeSafeMatchingRoutine.findMatch(RuntimeSafeMatchingRoutine.java:60)
		at org.scijava.ops.api.features.MatchingRoutine.match(MatchingRoutine.java:43)
		at org.scijava.ops.engine.matcher.impl.DefaultOpMatcher.match(DefaultOpMatcher.java:66)
		... 36 more
	Suppressed: org.scijava.ops.api.features.OpMatchingException: Unable to find an Op adaptation for org.scijava.ops.api.features.MatchingConditions@14eb64f2
		at org.scijava.ops.engine.matcher.adapt.AdaptationMatchingRoutine.findMatch(AdaptationMatchingRoutine.java:157)
		at org.scijava.ops.api.features.MatchingRoutine.match(MatchingRoutine.java:43)
		at org.scijava.ops.engine.matcher.impl.DefaultOpMatcher.match(DefaultOpMatcher.java:66)
		... 36 more
	Suppressed: org.scijava.ops.api.features.OpMatchingException: No matching 'math.subtract/java.util.function.BiFunction<net.imagej.ImgPlus<net.imglib2.type.numeric.integer.UnsignedShortType>, net.imagej.ImgPlus<net.imglib2.type.numeric.integer.UnsignedShortType>, java.lang.Object>' op

Request:
-	Name: "math.subtract", Types: java.util.function.BiFunction<net.imagej.ImgPlus<net.imglib2.type.numeric.integer.UnsignedShortType>, net.imagej.ImgPlus<net.imglib2.type.numeric.integer.UnsignedShortType>, java.lang.Object>
Input Types: 
		* net.imagej.ImgPlus<net.imglib2.type.numeric.integer.UnsignedShortType>
		* net.imagej.ImgPlus<net.imglib2.type.numeric.integer.UnsignedShortType>
Output Type: 
		* java.lang.Object

Candidates:
-	 No candidates found!
		at org.scijava.ops.api.features.MatchingResult.singleMatch(MatchingResult.java:67)
		at org.scijava.ops.engine.matcher.impl.RuntimeSafeMatchingRoutine.findMatch(RuntimeSafeMatchingRoutine.java:60)
		at org.scijava.ops.api.features.MatchingRoutine.match(MatchingRoutine.java:43)
		at org.scijava.ops.engine.matcher.impl.DefaultOpMatcher.match(DefaultOpMatcher.java:66)
		... 36 more
```

**Comment by hinerm** [comment]
Our theory was that the problem was that the output type of `java.lang.Object` prevented lifters from matching to raise pixel-wise subtracts to work on these images.

I tested this with the following in Java:
```
		try (Context ctx = new Context()) {
			ImgOpener opener = new ImgOpener(ctx);
			var img =
					opener.openImgs("https://imagej.net/images/lymp.tif").get(0).getImg();
			var gauss = ops.op("filter.gauss").arity2().input(img, 3.0).apply();

			// subtract gauss blur from input image
			var oType = new Nil<ArrayImg<UnsignedByteType, ByteArray>>(){};
			var res = ops.op("math.subtract").arity2().input(img, gauss).outType(oType).apply();
			System.out.println(res);
		}
```

But it produces the same exception:
```
Request:
-	Name: "math.subtract", Types: java.util.function.BiFunction<net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.integer.UnsignedByteType, net.imglib2.img.basictypeaccess.array.ByteArray>, net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.integer.UnsignedByteType, net.imglib2.img.basictypeaccess.array.ByteArray>, net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.integer.UnsignedByteType, net.imglib2.img.basictypeaccess.array.ByteArray>>
Input Types: 
		* net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.integer.UnsignedByteType, net.imglib2.img.basictypeaccess.array.ByteArray>
		* net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.integer.UnsignedByteType, net.imglib2.img.basictypeaccess.array.ByteArray>
Output Type: 
		* net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.integer.UnsignedByteType, net.imglib2.img.basictypeaccess.array.ByteArray>
```

**Comment by elevans** [comment]
I don't know if this helps but `ops.op("convert.float32")` also errors out the same way when using it from Jython:

```python
#@ Img img

# get op environment
from org.scijava.ops.api import OpEnvironment
ops = OpEnvironment.getEnvironment()

# convert to 32-bit img
f_img = ops.op("convert.float32").arity1().input(img).apply()
```
Produces this stack trace:

```python
... 24 more
	Suppressed: org.scijava.ops.api.features.OpMatchingException: No matching 'convert.float32/java.util.function.Function<net.imagej.ImgPlus<net.imglib2.type.numeric.integer.UnsignedShortType>, java.lang.Object>' op

Request:
-	Name: "convert.float32", Types: java.util.function.Function<net.imagej.ImgPlus<net.imglib2.type.numeric.integer.UnsignedShortType>, java.lang.Object>
Input Types: 
		* net.imagej.ImgPlus<net.imglib2.type.numeric.integer.UnsignedShortType>
Output Type: 
		* java.lang.Object

Candidates:
-	 No candidates found!
		at org.scijava.ops.api.features.MatchingResult.singleMatch(MatchingResult.java:67)
		at org.scijava.ops.engine.matcher.impl.RuntimeSafeMatchingRoutine.findMatch(RuntimeSafeMatchingRoutine.java:60)
		at org.scijava.ops.api.features.MatchingRoutine.match(MatchingRoutine.java:43)
		at org.scijava.ops.engine.matcher.impl.DefaultOpMatcher.match(DefaultOpMatcher.java:66)
		... 37 more
	Suppressed: org.scijava.ops.api.features.OpMatchingException: Unable to find an Op adaptation for org.scijava.ops.api.features.MatchingConditions@9cb269ef
		at org.scijava.ops.engine.matcher.adapt.AdaptationMatchingRoutine.findMatch(AdaptationMatchingRoutine.java:157)
		at org.scijava.ops.api.features.MatchingRoutine.match(MatchingRoutine.java:43)
		at org.scijava.ops.engine.matcher.impl.DefaultOpMatcher.match(DefaultOpMatcher.java:66)
		... 37 more
	Suppressed: org.scijava.ops.api.features.OpMatchingException: No matching 'convert.float32/java.util.function.Function<net.imagej.ImgPlus<net.imglib2.type.numeric.integer.UnsignedShortType>, java.lang.Object>' op

Request:
-	Name: "convert.float32", Types: java.util.function.Function<net.imagej.ImgPlus<net.imglib2.type.numeric.integer.UnsignedShortType>, java.lang.Object>
Input Types: 
		* net.imagej.ImgPlus<net.imglib2.type.numeric.integer.UnsignedShortType>
Output Type: 
		* java.lang.Object

Candidates:
-	 No candidates found!
		at org.scijava.ops.api.features.MatchingResult.singleMatch(MatchingResult.java:67)
		at org.scijava.ops.engine.matcher.impl.RuntimeSafeMatchingRoutine.findMatch(RuntimeSafeMatchingRoutine.java:60)
		at org.scijava.ops.api.features.MatchingRoutine.match(MatchingRoutine.java:43)
		at org.scijava.ops.engine.matcher.impl.DefaultOpMatcher.match(DefaultOpMatcher.java:66)
		... 37 more
```

I also tried creating an output image for the op to see if that helped...it did not:

```python
#@ Img img

# get op environment
from org.scijava.ops.api import OpEnvironment
ops = OpEnvironment.getEnvironment()

# convert to 32-bit img
f_img = ops.op("create.img").arity1().input(img).apply()
f_img = ops.op("convert.float32").arity2().input(f_img, img).apply()
```

**Comment by hinerm** [comment]
> I don't know if this helps but `ops.op("convert.float32")` also errors out the same way when using it from Jython:

Currently I wouldn't expect Functions operating on images to work. Most algorithms are implemented as Computers on single types - they can be lifted to work on Images _or_ adapted to Functions, but currently not both (required to match a Function Op that operates on Images). Let me know if that doesn't make sense.

**Comment by hinerm** [comment]
I have outlined the problems and started exploring solutions on [this branch](https://github.com/scijava/incubator/tree/imagej/imagej-ops2/binary-math).

What I see as needing to happen:
- [ ] Add lift ops that only lift the first parameter to a iterable (e.g. so `math.add(Img, 5)` works)
- [ ] Matching needs to allow for one step of algorithmic adaptation (computer to function) and one step of lifting (pixel to image)
- [ ] https://github.com/scijava/scijava/issues/47 is not mandatory but I think important

**Comment by hinerm** [comment]
OK I thought I was done working on https://github.com/scijava/incubator/tree/imagej/imagej-ops2/convert-common-image-types

But matches like this with no `outType` specified don't work:

```
final Img<IntType> imgA = TestImgGeneration.intArray(true, 10, 10);
var imgC = (Img<IntType>)ops.binary("math.sub").input(imgA, new IntType(25)).apply();
```

I suspect they *have* to work because trying to make a `Nil<Img<IntType>>` is probably a nightmare in python? Does that intuition seem correct @elevans?

@gselzer any thoughts off the top of your head on why matching without an `outType` doesn't work, but with an `outType` does?

**Comment by gselzer** [comment]
@hinerm you're trying to look for a `BiFunction<Img<IntType>, IntType, Object>`. I'm guessing none exist, so it tries to adapt something. **Adaptation to `Function`s with an `Object` output is *super* tricky**.

You're probably trying use [this adapt Op](https://github.com/scijava/incubator/commit/45df8ad60921e29857b67fc142430211acc98ad5#diff-fbe0c44ae81a65619b5b622ade1ad5e9f7722582dc08eb57242f17d5ae04d8b4R88), right? The second Op dependency is then maybe [this guy](https://github.com/scijava/incubator/blob/54b8af3021886df2530a3d9b6dd861c879ba7a2f/scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/adapt/functional/ComputersToFunctionsViaFunction.java#L80), and *that* guy will need some `Function<RAII, RAIO>` creator - I'm guessing that can't be found because that `O` type is vacuous, since it's all coming from that `Object` output type.

**Comment by hinerm** [comment]
How devastating would it be for a match request with unspecified output to behave like matching an `Any` instead of `Object`? I feel like that is closer to the semantic meaning of leaving off output specification right?

**Comment by gselzer** [comment]
> @gselzer How devastating would it be for a match request with unspecified output to behave like matching an `Any` instead of `Object`? I feel like that is closer to the semantic meaning of leaving off output specification right?

You're right, I agree `Any` is better, although there may be some fun casting involved. I think it's worth a  try...
