### ISSUE TITLE
Unable to convert images to float32

### ISSUE THREAD

**Issue by elevans** [scijava/scijava#166]
I can't convert an image to `float32`. Both `apply()` and `compute()` fail with the stack traces below. To reproduce open the blobs image and use the minimal examples in the script editor:

Language: **Jython**

Using apply:
```python
#@ ImgPlus img
from org.scijava.ops.api import OpEnvironment

# get ops environment
ops = OpEnvironment.getEnvironment()

# convert input ImgPlus to float32
x = ops.op("convert.float32").arity1().input(img).apply()
```

The apply stack trace:
```java
Started New_.py at Tue Dec 12 15:27:41 CST 2023
Traceback (most recent call last):
  File "New_.py", line 6, in <module>
	at net.imagej.ops2.adapt.LiftComputersToRAI.lambda$lift11$0(LiftComputersToRAI.java:73)
	at net.imglib2.loops.FastCursorLoops$TwoCursorLoop.accept(FastCursorLoops.java:150)
	at net.imglib2.loops.LoopBuilder.lambda$runOnChunkUsingCursors$5(LoopBuilder.java:401)
	at net.imglib2.loops.LoopBuilder.lambda$forEachPixel$0(LoopBuilder.java:159)
	at net.imglib2.loops.LoopBuilder.runOnChunkUsingCursors(LoopBuilder.java:399)
	at net.imglib2.loops.LoopBuilder.lambda$runUsingCursors$4(LoopBuilder.java:391)
	at net.imglib2.parallel.DefaultTaskExecutor.lambda$forEachApply$1(DefaultTaskExecutor.java:118)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:845)
	at net.imglib2.parallel.ForkJoinExecutorService.invokeAll(ForkJoinExecutorService.java:126)
	at net.imglib2.parallel.DefaultTaskExecutor.forEachApply(DefaultTaskExecutor.java:121)
	at net.imglib2.loops.LoopBuilder.runUsingCursors(LoopBuilder.java:390)
	at net.imglib2.loops.LoopBuilder.forEachChunk(LoopBuilder.java:197)
	at net.imglib2.loops.LoopBuilder.forEachPixel(LoopBuilder.java:158)
	at net.imagej.ops2.adapt.LiftComputersToRAI.lambda$lift11$1(LiftComputersToRAI.java:73)
	at org.scijava.ops.engine.adapt.functional.ComputersToFunctionsViaFunction$Computer1ToFunction1ViaFunction.lambda$apply$0(ComputersToFunctionsViaFunction.java:72)
	at org.scijava.ops.engine.matcher.impl.OpWrappers$Function1OpWrapper$1GenericTypedFunction1.apply(OpWrappers.java:99)
	at org.scijava.ops.api.OpBuilder$Arity1_IV_OU.apply(OpBuilder.java:1699)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
java.lang.ClassCastException: java.lang.ClassCastException: class net.imglib2.type.numeric.integer.UnsignedByteType cannot be cast to class net.imglib2.type.numeric.real.FloatType (net.imglib2.type.numeric.integer.UnsignedByteType and net.imglib2.type.numeric.real.FloatType are in unnamed module of loader 'app')

	at org.python.core.Py.JavaError(Py.java:547)
	at org.python.core.Py.JavaError(Py.java:538)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:192)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:208)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx3.f$0(New_.py:6)
	at org.python.pycode._pyx3.call_function(New_.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:255)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:173)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassCastException: class net.imglib2.type.numeric.integer.UnsignedByteType cannot be cast to class net.imglib2.type.numeric.real.FloatType (net.imglib2.type.numeric.integer.UnsignedByteType and net.imglib2.type.numeric.real.FloatType are in unnamed module of loader 'app')
	at net.imagej.ops2.adapt.LiftComputersToRAI.lambda$lift11$0(LiftComputersToRAI.java:73)
	at net.imglib2.loops.FastCursorLoops$TwoCursorLoop.accept(FastCursorLoops.java:150)
	at net.imglib2.loops.LoopBuilder.lambda$runOnChunkUsingCursors$5(LoopBuilder.java:401)
	at net.imglib2.loops.LoopBuilder.lambda$forEachPixel$0(LoopBuilder.java:159)
	at net.imglib2.loops.LoopBuilder.runOnChunkUsingCursors(LoopBuilder.java:399)
	at net.imglib2.loops.LoopBuilder.lambda$runUsingCursors$4(LoopBuilder.java:391)
	at net.imglib2.parallel.DefaultTaskExecutor.lambda$forEachApply$1(DefaultTaskExecutor.java:118)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:845)
	at net.imglib2.parallel.ForkJoinExecutorService.invokeAll(ForkJoinExecutorService.java:126)
	at net.imglib2.parallel.DefaultTaskExecutor.forEachApply(DefaultTaskExecutor.java:121)
	at net.imglib2.loops.LoopBuilder.runUsingCursors(LoopBuilder.java:390)
	at net.imglib2.loops.LoopBuilder.forEachChunk(LoopBuilder.java:197)
	at net.imglib2.loops.LoopBuilder.forEachPixel(LoopBuilder.java:158)
	at net.imagej.ops2.adapt.LiftComputersToRAI.lambda$lift11$1(LiftComputersToRAI.java:73)
	at org.scijava.ops.engine.adapt.functional.ComputersToFunctionsViaFunction$Computer1ToFunction1ViaFunction.lambda$apply$0(ComputersToFunctionsViaFunction.java:72)
	at org.scijava.ops.engine.matcher.impl.OpWrappers$Function1OpWrapper$1GenericTypedFunction1.apply(OpWrappers.java:99)
	at org.scijava.ops.api.OpBuilder$Arity1_IV_OU.apply(OpBuilder.java:1699)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:190)
	... 24 more
```

Using a computer:
```python
#@ ImgPlus img
from org.scijava.ops.api import OpEnvironment

# get ops environment
ops = OpEnvironment.getEnvironment()

# convert input ImgPlus to float32
result = ops.op("create.img").arity1().input(img).apply()
ops.op("convert.float32").arity1().input(img).output(result).compute()
```
The computer stack trace (truncated here because its very long and reptative):
```java
	at org.scijava.ops.engine.matcher.impl.DefaultOpMatcher.agglomeratedException(DefaultOpMatcher.java:80)
	at org.scijava.ops.engine.matcher.impl.DefaultOpMatcher.match(DefaultOpMatcher.java:74)
	at org.scijava.ops.engine.impl.DefaultOpEnvironment.findOpCandidate(DefaultOpEnvironment.java:520)
	at org.scijava.ops.engine.impl.DefaultOpEnvironment.generateCacheHit(DefaultOpEnvironment.java:497)
	at org.scijava.ops.engine.impl.DefaultOpEnvironment.findOp(DefaultOpEnvironment.java:430)
	at org.scijava.ops.engine.impl.DefaultOpEnvironment.op(DefaultOpEnvironment.java:242)
	at org.scijava.ops.api.OpBuilder.matchComputerHelper(OpBuilder.java:16561)
	at org.scijava.ops.api.OpBuilder.matchComputer(OpBuilder.java:16398)
	at org.scijava.ops.api.OpBuilder$Arity1_IV_OV.computer(OpBuilder.java:1760)
	at org.scijava.ops.api.OpBuilder$Arity1_IV_OV.compute(OpBuilder.java:1769)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
org.scijava.ops.api.OpMatchingException: org.scijava.ops.api.OpMatchingException: No MatchingRoutine was able to produce a match!

	at org.python.core.Py.JavaError(Py.java:547)
	at org.python.core.Py.JavaError(Py.java:538)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:192)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:208)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx51.f$0(/home/edward/Documents/repos/elevans/fiji-scripts/imagej2/filters/2D_gaussian_subtraction_sjo.py:10)
	at org.python.pycode._pyx51.call_function(/home/edward/Documents/repos/elevans/fiji-scripts/imagej2/filters/2D_gaussian_subtraction_sjo.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:255)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:173)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.scijava.ops.api.OpMatchingException: No MatchingRoutine was able to produce a match!
	at org.scijava.ops.engine.matcher.impl.DefaultOpMatcher.agglomeratedException(DefaultOpMatcher.java:80)
	at org.scijava.ops.engine.matcher.impl.DefaultOpMatcher.match(DefaultOpMatcher.java:74)
	at org.scijava.ops.engine.impl.DefaultOpEnvironment.findOpCandidate(DefaultOpEnvironment.java:520)
	at org.scijava.ops.engine.impl.DefaultOpEnvironment.generateCacheHit(DefaultOpEnvironment.java:497)
	at org.scijava.ops.engine.impl.DefaultOpEnvironment.findOp(DefaultOpEnvironment.java:430)
	at org.scijava.ops.engine.impl.DefaultOpEnvironment.op(DefaultOpEnvironment.java:242)
	at org.scijava.ops.api.OpBuilder.matchComputerHelper(OpBuilder.java:16561)
	at org.scijava.ops.api.OpBuilder.matchComputer(OpBuilder.java:16398)
	at org.scijava.ops.api.OpBuilder$Arity1_IV_OV.computer(OpBuilder.java:1760)
	at org.scijava.ops.api.OpBuilder$Arity1_IV_OV.compute(OpBuilder.java:1769)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:190)
	... 24 more
	Suppressed: org.scijava.ops.api.OpMatchingException: No matching 'convert.float32/org.scijava.function.Computers.Arity1<net.imagej.ImgPlus<net.imglib2.type.numeric.integer.UnsignedByteType>, net.imglib2.img.planar.PlanarImg<net.imglib2.type.numeric.integer.UnsignedByteType, net.imglib2.img.basictypeaccess.array.ByteArray>>' op

Request:
-	Name: "convert.float32", Types: org.scijava.function.Computers.Arity1<net.imagej.ImgPlus<net.imglib2.type.numeric.integer.UnsignedByteType>, net.imglib2.img.planar.PlanarImg<net.imglib2.type.numeric.integer.UnsignedByteType, net.imglib2.img.basictypeaccess.array.ByteArray>>
Input Types: 
		* net.imagej.ImgPlus<net.imglib2.type.numeric.integer.UnsignedByteType>
		* net.imglib2.img.planar.PlanarImg<net.imglib2.type.numeric.integer.UnsignedByteType, net.imglib2.img.basictypeaccess.array.ByteArray>
Output Type: 
		* net.imglib2.img.planar.PlanarImg<net.imglib2.type.numeric.integer.UnsignedByteType, net.imglib2.img.basictypeaccess.array.ByteArray>

Candidates:
-	 No candidates found!
		at org.scijava.ops.engine.matcher.MatchingResult.singleMatch(MatchingResult.java:96)
		at org.scijava.ops.engine.matcher.impl.RuntimeSafeMatchingRoutine.findMatch(RuntimeSafeMatchingRoutine.java:87)
		at org.scijava.ops.engine.matcher.MatchingRoutine.match(MatchingRoutine.java:73)
		at org.scijava.ops.engine.matcher.impl.DefaultOpMatcher.match(DefaultOpMatcher.java:66)
		... 37 more
	Suppressed: org.scijava.ops.api.OpMatchingException: Unable to find an Op adaptation for org.scijava.ops.engine.MatchingConditions@f6428f8a
		at org.scijava.ops.engine.matcher.adapt.AdaptationMatchingRoutine.findMatch(AdaptationMatchingRoutine.java:191)
		at org.scijava.ops.engine.matcher.MatchingRoutine.match(MatchingRoutine.java:73)
		at org.scijava.ops.engine.matcher.impl.DefaultOpMatcher.match(DefaultOpMatcher.java:66)
		... 37 more
		Suppressed: org.scijava.ops.api.OpMatchingException: No MatchingRoutine was able to produce a match!
			at org.scijava.ops.engine.matcher.impl.DefaultOpMatcher.agglomeratedException(DefaultOpMatcher.java:80)
			at org.scijava.ops.engine.matcher.impl.DefaultOpMatcher.match(DefaultOpMatcher.java:74)
			at org.scijava.ops.engine.matcher.adapt.AdaptationMatchingRoutine.findMatch(AdaptationMatchingRoutine.java:171)
			... 39 more
			Suppressed: org.scijava.ops.api.OpMatchingException: No matching 'convert.float32/org.scijava.function.Computers.Arity1<net.imglib2.type.numeric.integer.UnsignedByteType, net.imglib2.type.numeric.integer.UnsignedByteType>' op

Request:
-	Name: "convert.float32", Types: org.scijava.function.Computers.Arity1<net.imglib2.type.numeric.integer.UnsignedByteType, net.imglib2.type.numeric.integer.UnsignedByteType>
Input Types: 
		* net.imglib2.type.numeric.integer.UnsignedByteType
		* net.imglib2.type.numeric.integer.UnsignedByteType
Output Type: 
		* net.imglib2.type.numeric.integer.UnsignedByteType

Candidates:
-	 No candidates found!
				at org.scijava.ops.engine.matcher.MatchingResult.singleMatch(MatchingResult.java:96)
				at org.scijava.ops.engine.matcher.impl.RuntimeSafeMatchingRoutine.findMatch(RuntimeSafeMatchingRoutine.java:87)
				at org.scijava.ops.engine.matcher.MatchingRoutine.match(MatchingRoutine.java:73)
				at org.scijava.ops.engine.matcher.impl.DefaultOpMatcher.match(DefaultOpMatcher.java:66)
				... 40 more
			Suppressed: org.scijava.ops.api.OpMatchingException: Adaptation is not suitable: Adaptation is disabled
				at org.scijava.ops.engine.matcher.adapt.AdaptationMatchingRoutine.checkSuitability(AdaptationMatchingRoutine.java:76)
				at org.scijava.ops.engine.matcher.MatchingRoutine.match(MatchingRoutine.java:72)
				at org.scijava.ops.engine.matcher.impl.DefaultOpMatcher.match(DefaultOpMatcher.java:66)
				... 40 more
			Suppressed: org.scijava.ops.api.OpMatchingException: No matching 'convert.float32/org.scijava.function.Computers.Arity1<net.imglib2.type.numeric.integer.UnsignedByteType, net.imglib2.type.numeric.integer.UnsignedByteType>' op

Request:
-	Name: "convert.float32", Types: org.scijava.function.Computers.Arity1<net.imglib2.type.numeric.integer.UnsignedByteType, net.imglib2.type.numeric.integer.UnsignedByteType>
Input Types: 
		* net.imglib2.type.numeric.integer.UnsignedByteType
		* net.imglib2.type.numeric.integer.UnsignedByteType
Output Type: 
		* net.imglib2.type.numeric.integer.UnsignedByteType

Candidates:
-	 No candidates found!
				at org.scijava.ops.engine.matcher.MatchingResult.singleMatch(MatchingResult.java:96)
				at org.scijava.ops.engine.matcher.simplify.SimplificationMatchingRoutine.findMatch(SimplificationMatchingRoutine.java:130)
				at org.scijava.ops.engine.matcher.MatchingRoutine.match(MatchingRoutine.java:73)
				at org.scijava.ops.engine.matcher.impl.DefaultOpMatcher.match(DefaultOpMatcher.java:66)
				... 40 more
		Suppressed: org.scijava.ops.api.OpMatchingException: No MatchingRoutine was able to produce a match!
			at org.scijava.ops.engine.matcher.impl.DefaultOpMatcher.agglomeratedException(DefaultOpMatcher.java:80)
			at org.scijava.ops.engine.matcher.impl.DefaultOpMatcher.match(DefaultOpMatcher.java:74)
			at org.scijava.ops.engine.matcher.adapt.AdaptationMatchingRoutine.findMatch(AdaptationMatchingRoutine.java:171)
			... 39 more
			Suppressed: org.scijava.ops.api.OpMatchingException: No matching 'convert.float32/java.util.function.Function<net.imagej.ImgPlus<net.imglib2.type.numeric.integer.UnsignedByteType>, net.imglib2.img.planar.PlanarImg<net.imglib2.type.numeric.integer.UnsignedByteType, net.imglib2.img.basictypeaccess.array.ByteArray>>' op
...
```

**Comment by gselzer** [comment]
I looked a little bit at the function issue here, and the solution would be really involved. Basically, you're going to end up calling a very compilated adaptation process, and because you don't specify the output type Ops doesn't know what type of output image to give you. So it creates an image of `ShortType`s, which can't do the conversion.

So with that said, I'm pretty tired of trying to run convert through the adaptation process - I'm really starting to think that we should just make `Function`s that work on `Img`s, because this isn't the first time we've run into this and conversion called as a function is so hard to do well. @hinerm  do you have thoughts?

I'm surprised your computer version gets past the `create` call, because I didn't think that it could create from an `ImgPlus`. But it does, which is surprising, but then it creates a `UnsignedByteType` image, which of course cannot be the output of a `convert.float32` call :sweat_smile:

**Comment by elevans** [comment]
Thanks for looking into this @gselzer. As we discussed earlier this morning an easy work around (and maybe ideal) is to create a float image for the computer:

```python
from org.scijava.ops.api import OpEnvironment
from net.imglib2.type.numeric.real import FloatType

# get ops environment
ops = OpEnvironment.getEnvironment()

# convert input ImgPlus to float32
img_float = ops.op("create.img").arity2().input(img, FloatType()).apply()
ops.op("convert.float32").arity1().input(img).output(img_float).compute()
```
