### ISSUE TITLE
Ops implementing the same method with different type parameters produce null descriptions

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#95]
The [Member.description](https://github.com/scijava/incubator/blob/2a3e3c93d9f648174e64aa37badceb8ec9376ab1/scijava/scijava-struct/src/main/java/org/scijava/struct/Member.java#L20) claims to always return non-`null`. However, when attempting to print a list of all ops I get this `NullPointerException`, which runs into an NPE [here](https://github.com/scijava/incubator/blob/2a3e3c93d9f648174e64aa37badceb8ec9376ab1/scijava/scijava-ops-api/src/main/java/org/scijava/ops/api/OpInfo.java#L161):

```
java.lang.NullPointerException
	at org.scijava.ops.api@0-SNAPSHOT/org.scijava.ops.api.OpInfo.appendParam(OpInfo.java:161)
	at org.scijava.ops.api@0-SNAPSHOT/org.scijava.ops.api.OpInfo.opString(OpInfo.java:137)
	at org.scijava.ops.api@0-SNAPSHOT/org.scijava.ops.api.OpInfo.opString(OpInfo.java:123)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.matcher.impl.OpClassInfo.toString(OpClassInfo.java:201)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at net.imagej.ops2@0-SNAPSHOT/net.imagej.ops2.OpRegressionTest.opDescriptionRegressionIT(OpRegressionTest.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:84)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

**Comment by hinerm** [comment]
@gselzer see [this branch](https://github.com/scijava/incubator/tree/imagej/imagej-ops2/null-op-descriptions) for a simple unit test reproducing the issue.

**Comment by hinerm** [comment]
@gselzer after more debugging I added [another test](https://github.com/scijava/incubator/commit/68aa654f669f65b73dda5aa1b12dac9909696495) which shows the problem more clearly:

When two ops implement the same generic method with different type parameters, they are mapped to the same [MethodParamInfo by the paramDataMap](https://github.com/scijava/incubator/blob/a245ba7e6a33241ec5d3d72e7c034b37791ab783/scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/struct/LazilyGeneratedMethodParameterData.java#L67). This `MethodParamInfo` will then fail [at the point of retrieval](https://github.com/scijava/incubator/blob/a245ba7e6a33241ec5d3d72e7c034b37791ab783/scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/struct/MethodParamInfo.java#L23) because its map contains they keys of the *other* implementation.

The two possible solutions that first come to my mind are:
1. The `paramDataMap` needs to be keyed on something other than just `Method` that takes the type params of the method into account
1. The `MethodParamInfo` need to be populated with names/descriptions for *all* implementations of a given method. So the checks in `LazilyGeneratedMethodParameterData` would have to be two-stage: a) is there a method entry? and b) does that method have entries for this `fmt`? If not, update it.

Option `2` seems easier to me.. I'm going to try implementing it now and see if it works and is as straightforward as I think.

**Comment by hinerm** [comment]
@gselzer @ctrueden thoughts on https://github.com/scijava/incubator/commit/1f53b17b80f140a98ab16cef58b028f53dcf0add? I don't love exposing the maps and making them modifiable but it does work.

Side note: what formatter is used with incubator?

**Comment by gselzer** [comment]
> Side note: what formatter is used with incubator?

[This guy](https://github.com/scijava/scijava-coding-style)

**Comment by hinerm** [comment]
>@gselzer @ctrueden thoughts on https://github.com/scijava/incubator/commit/1f53b17b80f140a98ab16cef58b028f53dcf0add?

Also it looks like this change may be insufficient 😞

**Comment by hinerm** [comment]
>Also it looks like this change may be insufficient

I thiiiink this may be because `MethodParamInfo`'s maps are keyed on [`FunctionalMethodType`](https://github.com/scijava/incubator/blob/a245ba7e6a33241ec5d3d72e7c034b37791ab783/scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/struct/MethodParamInfo.java#L8-L9) which don't implement `hashCode`/`equals`.. gotta test

**Comment by hinerm** [comment]
>Also it looks like this change may be insufficient

So, in Eclipse, when running from the `OpRegressionTest` class directly it passes... but when doing a `<right-click>` > `Run As` > `JUnit Test` on the `imagej-ops2` *component* then the same test fails (as it does on the command line).
